// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiYfdQjU0ZZfdI7raOIQQBO56hAiMmJ-k',
    appId: '1:281892166305:web:29b28ef5bf28f9f4182ee0',
    messagingSenderId: '281892166305',
    projectId: 'food-fusion-eb9dd',
    authDomain: 'food-fusion-eb9dd.firebaseapp.com',
    storageBucket: 'food-fusion-eb9dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI07kJ6DpSLj4H99slmmfJmFW0MobhxTs',
    appId: '1:281892166305:android:e43f3cba81cbf405182ee0',
    messagingSenderId: '281892166305',
    projectId: 'food-fusion-eb9dd',
    storageBucket: 'food-fusion-eb9dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PiqsECoMA7VvXCxmRBeQeCPHt96NORw',
    appId: '1:281892166305:ios:1cbd66045c929e72182ee0',
    messagingSenderId: '281892166305',
    projectId: 'food-fusion-eb9dd',
    storageBucket: 'food-fusion-eb9dd.firebasestorage.app',
    iosBundleId: 'com.example.foodfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PiqsECoMA7VvXCxmRBeQeCPHt96NORw',
    appId: '1:281892166305:ios:1cbd66045c929e72182ee0',
    messagingSenderId: '281892166305',
    projectId: 'food-fusion-eb9dd',
    storageBucket: 'food-fusion-eb9dd.firebasestorage.app',
    iosBundleId: 'com.example.foodfusion',
  );
}
